
set(WIRECTRLD_INSTALL_DIR_EXE           "/usr/sbin")
set(WIRECTRLD_INSTALL_DIR_DBUS_CONF     "/etc/dbus-1/system.d/")
set(WIRECTRLD_INSTALL_DIR_SYSTEMD_SVC   "/etc/systemd/system/")
set(WIRECTRLD_INSTALL_DIR_WIRECTRLD_CONF "/etc/wirectrl/")

set(WIRECTRLD_INSTALL_NAME_PREFIX       "de.titnc.pi.wirectrl")

install(FILES ./scripts/dbus.conf
        DESTINATION ${WIRECTRLD_INSTALL_DIR_DBUS_CONF}
        RENAME ${WIRECTRLD_INSTALL_NAME_PREFIX}.conf
        PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
)
install(FILES ./scripts/system.d.service
        DESTINATION ${WIRECTRLD_INSTALL_DIR_SYSTEMD_SVC}
        RENAME wirectrl.service
        PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
)
install(FILES ./scripts/wirectrl.conf
        DESTINATION ${WIRECTRLD_INSTALL_DIR_WIRECTRLD_CONF}
        RENAME wirectrld.conf
        PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
)
install(TARGETS wirectrld
        DESTINATION     ${WIRECTRLD_INSTALL_DIR_EXE}
        PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ WORLD_READ
)
